[package]
name = "bdk_testenv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoincore-rpc = { version = "0.17" }
bdk_chain = { path = "../chain", version = "0.11", default-features = false }
anyhow = { version = "1" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
bitcoincore-rpc = { version = "0.17" }
bdk_chain = { path = "../chain", version = "0.11", default-features = false }
anyhow = { version = "1" }
electrsd = { version = "0.26.0", features = ["legacy"] }

[features]
default = ["std"]
std = ["bdk_chain/std"]
serde = ["bdk_chain/serde"]
